"""Regenerate tests/fixtures/*.npz and the golden reference outputs.

This is NOT run as part of the test suite -- the tests read the small
.npz/.nml fixture files this script writes, so they don't need the
external MESA grid at test time. Run this script by hand:

  1) to (re)build the track fixtures the first time, or
  2) to regenerate golden_outputs.npz after an *intentional* change to
     pyrotwind's physics (never to "make a failing test pass" without
     understanding why the output changed).

Track fixtures are built from a real MESA single-star model grid (the
same one src/rotevol.ipynb uses), so this needs that grid available
locally -- pass its path as the one argument, or edit GRID_PATH below.
Golden outputs are generated by calling the *currently built*
pyrotwind.rotwind(), so rebuild the .so from your intended source before
running this.
"""
import sys
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
FIXTURES = HERE / "fixtures"
GRID_PATH = "/Users/yaguang/gdrive/density-mergers/models/single.parquet"

TRACK_COLS = [
    "taucouple", "taucouplecm", "sage", "sl", "sr", "steffl", "smcz",
    "srcz", "sxc", "si", "sie", "sic", "sicore", "staucz", "shec", "sp", "sm",
]

# (fixture name, star_mass, number of leading rows to keep after sorting
# by age). "dense" tracks keep the model grid's native (unstrided) time
# resolution and are truncated early enough to actually grow and evolve
# a helium core within their range -- this is what exercises int3zone's
# three-zone dynamics for real, not just the fully-convective/two-zone
# fallback paths threezoneevol also has to handle.
TRACK_SPECS = [
    ("dense_m1.0", 1.0, 2000),
    ("dense_m1.5", 1.5, 2000),
]

NML_TEMPLATE = """
&const
  cg   = 6.6725d-8
  cc23 = 0.6666666666666667d0
  cpi     = 3.1415926535898d0
  csecday = 86400.0d0
  csecyr  = 3.1556952d7
  solm = 1.9891d33
  solr = 6.9598d10
  soll = 3.8418d33
  solp   = 100179.864d0
  soltau = 717053.416d0
  solprot = 25.4d0
/

&wind_params
  lsolid  = {lsolid}
  lthreezone = {lthreezone}
  iwind   = 3
  lross   = .true.
  pmma = 2.0d0
  pmmb = 1.0d0
  pmmc = 0.0d0
  pmmm = 0.22d0
  fk = 5.655d0
  soljdot = 1.3d30
  solmdot = 1.27d12
  wcrit  = 3.863d-5
  rocrit = 0.91d0
  pdisk = 4.0d0
  tlock = 10.0d0
/
"""

NML_SPECS = {
    "nml_solid": dict(lsolid=".true.", lthreezone=".true."),
    "nml_twozone": dict(lsolid=".false.", lthreezone=".false."),
    "nml_threezone": dict(lsolid=".false.", lthreezone=".true."),
}


def build_track(df, mass, nrows):
    m = df["star_mass"] == mass
    m &= df["stage"].isin(["ms", "rgb"])
    track = df.loc[m].sort_values("star_age").reset_index(drop=True)
    track = track.iloc[:nrows].reset_index(drop=True)

    track["sage"] = track["star_age"] / 1e9
    track["sl"] = 10.0 ** track["log_L"]
    track["sr"] = 10.0 ** track["log_R"]
    track["steffl"] = 10.0 ** track["log_Teff"]
    track["smcz"] = track["m_ocz_bot"] / 1.9891e33
    track["srcz"] = track["r_ocz_bot"]
    track["sxc"] = 0.0
    track["shec"] = 0.0
    track["si"] = track["I_tot"]
    track["sic"] = track["I_c"]
    track["sicore"] = track["I_core"]
    track["sie"] = track["I_env"]
    track["staucz"] = track["ocz_turnover_time_bot_Hp"]
    track["sp"] = track["P_phot"]
    track["sm"] = track["star_mass"]

    taucouple = (track["star_mass"].iloc[0]) ** (-3.800) * 22 * 1e6 * 4
    track["taucouple"] = taucouple
    track["taucouplecm"] = taucouple
    tm = 10.0 ** track["log_R"] >= 2.7
    track.loc[tm, "taucouple"] = taucouple * 0.5 * (
        10.0 ** track.loc[tm, "log_R"] / 10.0 ** track.loc[tm, "log_R"].iloc[0]
    ) ** -3
    track.loc[tm, "taucouplecm"] = taucouple * 100

    return track


def write_tracks(grid_path):
    df = pd.read_parquet(grid_path)
    solm, solr = 1.9891e33, 6.9598e10
    df["I_core"] = 2.0 / 3.0 * df["he_core_mass"] * solm * (df["he_core_radius"] * solr) ** 2.0
    df["I_c"] = df["I_tot"] - df["I_env"] - df["I_core"]

    for name, mass, nrows in TRACK_SPECS:
        track = build_track(df, mass, nrows)
        arrs = {c: track[c].to_numpy(dtype="float64") for c in TRACK_COLS}
        np.savez(FIXTURES / f"track_{name}.npz", **arrs)
        print(f"wrote track_{name}.npz: nm={len(track)}, "
              f"sicore>0 at {int(np.sum(arrs['sicore'] > 0))}/{len(track)} points")


def write_namelists():
    for name, params in NML_SPECS.items():
        (FIXTURES / f"{name}.nml").write_text(NML_TEMPLATE.format(**params))
        print(f"wrote {name}.nml")


def write_golden_outputs():
    sys.path.insert(0, str(HERE.parent))
    import pyrotwind

    out_names = ["swe", "swc", "swcore", "sj", "sje", "sjc", "sjcore", "sprot", "faccen"]
    results = {}
    for nml_name in NML_SPECS:
        pyrotwind.constm.init_const(str(FIXTURES / f"{nml_name}.nml"))
        pyrotwind.params.read_wind_params(str(FIXTURES / f"{nml_name}.nml"))
        for track_name, _, _ in TRACK_SPECS:
            d = np.load(FIXTURES / f"track_{track_name}.npz")
            nm = len(d["sage"])
            out = pyrotwind.rotwind(
                d["taucouple"], d["taucouplecm"], d["sage"], d["sl"], d["sr"],
                d["steffl"], d["smcz"], d["srcz"], d["sxc"], d["si"], d["sie"],
                d["sic"], d["sicore"], d["staucz"], d["shec"], d["sp"], d["sm"], nm,
            )
            key = f"{nml_name}__{track_name}"
            for out_name, arr in zip(out_names, out[:-1]):
                results[f"{key}__{out_name}"] = arr
            results[f"{key}__iermsg"] = np.array(out[-1])
            print(f"{key}: iermsg={out[-1]}")
    np.savez(FIXTURES / "golden_outputs.npz", **results)
    print(f"wrote golden_outputs.npz ({len(results)} arrays)")


if __name__ == "__main__":
    grid_path = sys.argv[1] if len(sys.argv) > 1 else GRID_PATH
    write_tracks(grid_path)
    write_namelists()
    write_golden_outputs()
